#1. Working PyTorch Tensors

##1.1. Creating and Initalizing Tensor

In [1]:
import torch
print(torch.__version__)

1.4.0


In [5]:
# current default floating point torch.dtype
print(torch.get_default_dtype())
# default dtype for a tensor can only be a float type
torch.set_default_dtype(torch.int)

torch.float32


TypeError: ignored

In [6]:
# Set the default floating point to torch.float64
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

###1.1.1. Creating Tensors

In [8]:
# A Tensor initialized with a specific array, the torch tensor always creates a copy of the data
# torch.Tensor() contains torch.tensor() and torch.empty()
tensor_arr = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f'Is tensor_arr a tensor? {torch.is_tensor(tensor_arr)}, and how it looks like. {tensor_arr}')

Is tensor_arr a tensor? True, and how it looks like. tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
torch.numel(tensor_arr) # to return the number of elements in a tensor

6

In [11]:
# An un-initialized Tensor of shape 2*2 allocated space in memory
# tensor_uninitialized = torch.tensor(2, 2) return error
tensor_uninitialized = torch.Tensor(2, 2) # randomly generated number
tensor_uninitialized

tensor([[ 3.4150e-316,  1.3340e-322],
        [-3.3846e+125,   1.4917e+20]])

In [12]:
# A tensor of size 2*2 initialized with random values
tensor_initialized = torch.rand(2, 2)
tensor_initialized

tensor([[0.1953, 0.0434],
        [0.2935, 0.0937]])

In [13]:
# Tensors can be set to have specific data types
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [14]:
# A Tensor of type short
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [15]:
# A Tensor of type float half
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [16]:
# A tensor filled with a specific values
tensor_fill = torch.full((2, 6), fill_value=10)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [17]:
# A tensor of size (2, 4) containing all ones
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [18]:
# A tensor of size (2, 4) like tensor_of_ones containing all zeros
tensors_of_zeroes = torch.zeros_like(tensor_of_ones)
tensors_of_zeroes

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [19]:
# Create an identity 5*5 tensor
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
# Get the list of indices of non-zero elements in a tensor
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [22]:
# Create a sparse tensor using coordinates specified by indices and values
i = torch.tensor([
                  [0, 1, 1],
                  [2, 2, 0]
])
v = torch.tensor([3, 4, 5], dtype=torch.float32)
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [24]:
print(sparse_tensor.to_dense())

tensor([[0., 0., 3., 0., 0.],
        [5., 0., 4., 0., 0.]], dtype=torch.float32)


##1.2. Inplace / Out-of-place

The first difference is taht ALL operations on the tensor that operate in-place on it will have an "\_" postfix. For example, add is the out-of-place version, and add_ is the in-place version

In [25]:
initial_tensor = torch.rand(2, 3)
initial_tensor

tensor([[0.3831, 0.2636, 0.0816],
        [0.1635, 0.7639, 0.8437]])

In [26]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [27]:
initial_tensor.fill(10)

AttributeError: ignored

In [28]:
# the add() method does an out-of-place add operation and returns a new tensor
new_tensor = initial_tensor.add(5)
print(new_tensor, initial_tensor)

tensor([[15., 15., 15.],
        [15., 15., 15.]]) tensor([[10., 10., 10.],
        [10., 10., 10.]])


In [29]:
# the add_() method does an in-place add, changing the calling tensor
initial_tensor.add_(8)
print(initial_tensor)

tensor([[18., 18., 18.],
        [18., 18., 18.]])


In [30]:
# the new_tensor was a separate copy and is unaffected
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [31]:
# in-palce version of sqrt()
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

##1.3. Indexing, Slicing, Joining, Mutating Ops

In [32]:
# Slicing
x = torch.linspace(start=0.1, end=1.0, steps=15)
x

tensor([0.1000, 0.1643, 0.2286, 0.2929, 0.3571, 0.4214, 0.4857, 0.5500, 0.6143,
        0.6786, 0.7429, 0.8071, 0.8714, 0.9357, 1.0000])

In [34]:
# Splits a tensor into a specific number of chunks
tensor_chunk =  torch.chunk(input=x, chunks=3, dim=0)
tensor_chunk

(tensor([0.1000, 0.1643, 0.2286, 0.2929, 0.3571]),
 tensor([0.4214, 0.4857, 0.5500, 0.6143, 0.6786]),
 tensor([0.7429, 0.8071, 0.8714, 0.9357, 1.0000]))

In [36]:
tensor_chunk =  torch.chunk(input=x, chunks=3, dim=-1)
tensor_chunk

(tensor([0.1000, 0.1643, 0.2286, 0.2929, 0.3571]),
 tensor([0.4214, 0.4857, 0.5500, 0.6143, 0.6786]),
 tensor([0.7429, 0.8071, 0.8714, 0.9357, 1.0000]))

In [37]:
# Concatenates the sequence of tensors along the given dimension
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])
torch.cat((tensor1, tensor2, tensor3), dim=0)

tensor([0.1000, 0.1643, 0.2286, 0.2929, 0.3571, 0.4214, 0.4857, 0.5500, 0.6143,
        0.6786, 3.0000, 4.0000, 5.0000])

In [39]:
random_tensor = torch.tensor([
                              [10, 8, 30],
                              [40, 5, 6],
                              [12, 2, 21]
])
random_tensor

tensor([[10,  8, 30],
        [40,  5,  6],
        [12,  2, 21]])

In [40]:
random_tensor[0, 1]

tensor(8)

In [41]:
random_tensor[1:, 1:]

tensor([[ 5,  6],
        [ 2, 21]])

In [52]:
# Splits the tensor into chunks
print(random_tensor.shape)
random_tensor_split = torch.split(random_tensor, 2, dim=0)
random_tensor_split

torch.Size([3, 3])


(tensor([[10,  8, 30],
         [40,  5,  6]]), tensor([[12,  2, 21]]))

In [53]:
random_tensor_split = torch.split(random_tensor, 2, dim=1)
random_tensor_split

(tensor([[10,  8],
         [40,  5],
         [12,  2]]), tensor([[30],
         [ 6],
         [21]]))

In [54]:
# View
random_tensor.size()

torch.Size([3, 3])

In [65]:
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([ 10,   8,  30,  40,   5,   6,  12,   2, 100])

In [58]:
resized_tensor = random_tensor.view(3, 3)
resized_tensor

tensor([[10,  8, 30],
        [40,  5,  6],
        [12,  2, 21]])

In [59]:
resized_tensor = random_tensor.view(9, 1)
resized_tensor

tensor([[10],
        [ 8],
        [30],
        [40],
        [ 5],
        [ 6],
        [12],
        [ 2],
        [21]])

In [60]:
resized_tensor.size()

torch.Size([9, 1])

In [68]:
random_tensor[2, 2] = 100.0
resized_tensor

tensor([ 10,   8,  30,  40,   5,   6,  12,   2, 100])

In [69]:
# Unsqueeze: returns a new tensor with a dimension of size one inserted at the specified position
random_tensor

tensor([[ 10,   8,  30],
        [ 40,   5,   6],
        [ 12,   2, 100]])

In [70]:
random_tensor.shape

torch.Size([3, 3])

In [71]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10],
         [  8],
         [ 30]],

        [[ 40],
         [  5],
         [  6]],

        [[ 12],
         [  2],
         [100]]])

In [72]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [73]:
# Transpose: Return a tensor that is a transposed version of input. 
# The given dimensions dim0 and dim1 are swapped.
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [75]:
tensor_transpose = torch.transpose(initial_tensor, dim0=0, dim1=1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [76]:
# Sorting Tensors
# Tensors can be sorted along a specified dimension. If no dimension is specified, 
# the last dimension is picked by default.
random_tensor

tensor([[ 10,   8,  30],
        [ 40,   5,   6],
        [ 12,   2, 100]])

In [77]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)
sorted_tensor

tensor([[  8,  10,  30],
        [  5,   6,  40],
        [  2,  12, 100]])

In [78]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

##1.4. Math Operations

In [79]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

In [80]:
# abs
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [81]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [82]:
new_tensor = torch.add(initial_tensor, 2)
new_tensor

tensor([[20., 20., 20.],
        [20., 20., 20.]])

In [83]:
torch.add(input=initial_tensor, other=10, out=new_tensor)

tensor([[28., 28., 28.],
        [28., 28., 28.]])

In [84]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))
add1 = rand1 + rand2
add1

tensor([[2.0073, 1.0256, 1.2723],
        [1.2679, 0.6658, 0.8845]])

In [91]:
# Elment-wise division
tensor = torch.tensor([
                       [-1, -2, -3],
                       [1, 2, 3]
]).type(torch.float32)
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]], dtype=torch.float32)

In [92]:
# Element-wise multiplication
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]], dtype=torch.float32)

In [93]:
# Clamp the value of a Tensor --> set upper and lower limits
tensor_clamp = torch.clamp(tensor, min=-0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]], dtype=torch.float32)

##1.5. Vector Multiplication

In [94]:
t1 = torch.tensor([1, 2])
t2 = torch.tensor([10, 20])
dot_product = torch.dot(t1, t2)
dot_product

tensor(50)

In [95]:
# Matrix Vector Product
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
vector = torch.tensor([0, 1, 2])
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8, 17])

In [96]:
# Matrix multiplication
another_matrix = torch.tensor([
                               [10, 30],
                               [20, 0],
                               [0, 50]
])
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50, 180],
        [140, 420]])

In [105]:
# Returns the indices of the maximum values of a tensor across a dimension
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

In [99]:
torch.argmin(matrix_mul, dim=1)

tensor([0, 0])